### ISSUE TITLE
Epic: Post MVP1 code cleanup & decisions for new code

### ISSUE THREAD

**Issue by fweingartshofer** [eddie-energy/eddie#101]
```[tasklist]
### Tasks
- [ ] #102
- [ ] https://github.com/eddie-energy/eddie/issues/148
- [ ] #121
- [ ] https://github.com/eddie-energy/eddie/issues/136
- [ ] #100
- [ ] #104
- [ ] #105
- [ ] #107
- [ ] #108
- [ ] #109
- [ ] #111
- [ ] #113
- [ ] #114
- [ ] #115
- [ ] https://github.com/eddie-energy/eddie/issues/118
- [ ] https://github.com/eddie-energy/eddie/issues/119
- [ ] https://github.com/eddie-energy/eddie/issues/122
- [ ] https://github.com/eddie-energy/eddie/issues/117
- [ ] https://github.com/eddie-energy/eddie/issues/441
- [ ] https://github.com/eddie-energy/eddie/issues/423
- [ ] #110
- [ ] https://github.com/eddie-energy/eddie/issues/451
- [ ] https://github.com/eddie-energy/eddie/issues/447
- [ ] #106
- [ ] https://github.com/eddie-energy/eddie/issues/463
- [ ] https://github.com/eddie-energy/eddie/issues/120
- [ ] #103
- [ ] #112
- [ ] https://github.com/eddie-energy/eddie/issues/258
- [ ] https://github.com/eddie-energy/eddie/issues/443
- [ ] https://github.com/eddie-energy/eddie/issues/459
- [ ] https://github.com/eddie-energy/eddie/issues/457
- [ ] https://github.com/eddie-energy/eddie/issues/522
- [ ] https://github.com/eddie-energy/eddie/issues/446
- [ ] https://github.com/eddie-energy/eddie/issues/448
- [ ] https://github.com/eddie-energy/eddie/issues/458
- [ ] https://github.com/eddie-energy/eddie/issues/438
- [x] Add JavaDoc (many classes have non and a brief description how the class should be used and what it's for would be useful)
- [ ] https://github.com/eddie-energy/eddie/issues/465
- [ ] https://github.com/eddie-energy/eddie/issues/467
- [ ] https://github.com/eddie-energy/eddie/issues/470
- [ ] https://github.com/eddie-energy/eddie/issues/450
- [ ] https://github.com/eddie-energy/eddie/issues/508
- [ ] https://github.com/eddie-energy/eddie/issues/509
- [x] Datadis Unit test for invalid credentials makes a network request (should be an integration test)
- [ ] https://github.com/eddie-energy/eddie/issues/516
- [ ] https://github.com/eddie-energy/eddie/issues/534
- [ ] https://github.com/eddie-energy/eddie/issues/460
- [ ] https://github.com/eddie-energy/eddie/issues/461
- [ ] https://github.com/eddie-energy/eddie/issues/407
```
