### ISSUE TITLE
Popup Redesign

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1026]
This requirement is used to track features and improvements on the EDDIE popup, transitioning it to its next visual and functional iteration. These changes mostly concern:
- Structure of information (especially of data needs)
- Streamlining region connector elements
- Communicating interaction steps to the user
- Enabling the eligible party to react to user interaction

## Design/UI/UX Requirements

The general user flow remains intact. A sketch of the envisioned changes can be found at https://app.uizard.io/p/ae445d7c/overview.
```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/602
- [x] Add a title to the EDDIE popup to indicate what it does ("Request for permission"?)
- [x] Add a note on what permission administrator to select as shown in attached sketch
- [ ] https://github.com/eddie-energy/eddie/issues/1029
- [ ] https://github.com/eddie-energy/eddie/issues/1097
- [ ] https://github.com/eddie-energy/eddie/issues/268
- [ ] https://github.com/eddie-energy/eddie/issues/1119
- [ ] https://github.com/eddie-energy/eddie/issues/1140
```
