### ISSUE TITLE
AIIDA: Multi-tenancy and cloud-capable

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#1227]
## Short Description
In recent demos, it has become evident that we need to implement a cloud-ready AIIDA very soon. Many SM real-time interfaces and smart appliances are already capable of transferring data to the cloud or back to OEM environments. Hence, we need to support these scenarios very soon.

In the Acceptance Criteria below, I listed a number of points that need to be achieved to consider the requirement fulfilled.

NOTE: Please understand this requirement rather as an epic that a single task or story.

## Acceptance Criteria
- [x] AIIDA must be secured/securable via logins. #1283
- [x] Show which user is logged in. #1493
- [x] Users must be able to manage their data/information. #849 
- [x] Users must be able to get insights on their domain over a dashboard. #1184
- [x] As a first step to support behind-the-meter assets, create a CIM data source. #1093 
- [x] Provide means to write back a message. #1331  
- [x] Deployment Strategy for Edge and Cloud. #1530
