### ISSUE TITLE
Implement the EDDIE Button as a Multistep Form

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1233]
## Short Description

The EDDIE button currently uses a lot of vertical space to fit all information inside the form dialog. This may overwhelm and discourage the user and also leads to layout shifts during interaction.

Instead of showing all information at once, the dialog can display similar fields in separate steps. Such steps may be
1. display of the data need
2. country and PA selection
3. RC form (metering point, access token)
4. RC post-request instructions and actions (accept, reject, continue)
5. success page

The actual steps and even the number of total steps may depend on the button configuration (presets) and data need (AIIDA).

As this change requires major design changes, it makes sense to also reconsider the existing design as a whole.

The final design is to be clearly defined in a high fidelity prototype. Further information is to be found in the respective ticket.

> [!WARNING] 
> The contents of this ticket might change during the research and design phase. 
> Some tasks and tickets are yet to be defined.

## Acceptance Criteria

- [x] Design has been approved in refinement
- [x] Design received and implemented feedback during refinement (and UVIE if possible)
- [x] Follow-up tickets are defined

## Design/UI/UX Requirements _(optional)_

The following image represents the general approach.

![eddie-multi-step-form](https://github.com/user-attachments/assets/c9ef6ae5-509f-4418-b7b0-3862caad06db)

Part of this ticket is to also
1. define the full user journey, including edge cases
2. create low-fidelity prototypes / sketches for different layouts
3. create a high-fidelity prototype of the chosen solution

## Tasks

- [x] https://github.com/eddie-energy/eddie/issues/1275
- [x] Create a medium to high-fidelity design of the EDDIE button as a multistep form
- [x] Implement the new design
- [x] #1027
- [x] https://github.com/eddie-energy/eddie/issues/1170
- [x] https://github.com/eddie-energy/eddie/issues/1386
- [x] https://github.com/eddie-energy/eddie/issues/1180
- [x] Update existing E2E tests
- [x] https://github.com/eddie-energy/eddie/issues/1371
- [x] Update RC element instructions with developers
- [x] https://github.com/eddie-energy/eddie/issues/1414
- [x] Conduct tests and user studies with developers
- [ ] Test implementation for accessibility (EAA, WCAG)
- [x] #1666
- [ ] Document for each RC which PA and steps can be used for testing
- [x] Configure all RCs in Docker for testing
- [x] Create E2E tests for multistep form
- [x] Run E2E tests on core dev page instead of example app?
- [x] Use colors from EDDIE website and logo in the EDDIE button where possible
- [x] Use EDDIE font (Poppins)
- [x] Fix fonts and line heights in permission dialog
- [ ] https://github.com/eddie-energy/eddie/issues/1473
- [ ] Animate view transitions
- [ ] Bug bash and feedback with devs (and demonstrators?)
