### ISSUE TITLE
AIIDA: Rework Data Needs

### ISSUE THREAD

**Issue by stefanpenzinger** [eddie-energy/eddie#1246]
## Short Description
Data Needs are currently focusing only on Smart Meters. In the future other devices such as energy management systems (LOXONE, KNX, etc.), heat pumps, EV chargers or in general _behind the meter_ devices should be compatible.

These devices should be categorised as _assset_ like a Smart Meter is a **MeasuredGridConnection** or an energy managements system is a **ControllableUnit**.

Different schemas should be requested over the data need such as _RAW DATA_, _CIM_ or  _SAREF_.
The kind of device should be defined in the data need.

Sometimes data has to be sent at a specific time, for this a CRON expression can be sent within the data need. 

Furthermore, AIIDA devices should also be able to not only send data but also receive data back from the eligible party in a bidirectional manner. This means AIIDA can either be source or sink or both.

One use case for bidirectional data transmission is that the grid operator can enable a flexible connection. Each customer has defined set points in the contract (e.g. 5 kW) that they are allowed to consume or generate. Based on the grid load of a specific transformer, these target values can be adjusted per customer. This enables a more flexible grid.

Example for a Data Need for a SmartMeter could be:  
```json
{
  "type": "genericAiida",
  "id": "35b5531c-6391-4ec1-8c78-17f8dc832d82",
  "name": "EDDIE Demo - Current Active Power",
  "description": "fetches data all 5s and shows current active power",
  "purpose": "fetches data all 5s and shows current active power",
  "policyLink": "https://eddie.energy/access_policy",
  "createdAt": "2024-09-03T08:21:19.834184Z",
  "duration": {
    "type": "relativeDuration",
    "start": "P0D",
    "end": "P3M"
  },
  "transmissionInterval": 2,
  "transmissionSchedule": "* * * * 10 * *",
  "transmissionDirection": "source/sink",
  "asset": "MeasuredGridConnection",
  "schema": [
    "SMARTMETER_P1_IEC_CIM",
    "SMARTMETER_RAW_DATA",
    "SMARTMETER_SAREF"
  ],
  "dataTags": [
    "1-0:1.7.0",
    "1-0:2.7.0"
  ]
}
```

## Acceptance Criteria
- [x] Implement Transmission Schedule in AIIDA ( #1219 )
- [x] Implement Assets in AIIDA ( #1247 )
- [x] Implement Schemas in AIIDA ( #1206 )
- [ ] Support AIIDA as source and sink ( #1331 )
- [ ] Think about the possibility to combine data needs which request AIIDA to send or receive data
