### ISSUE TITLE
Define the full user flow for the EDDIE button

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1275]
**What**
The goal is to define how the user would interact with the EDDIE button from clicking the button on the website of the eligible party, through the interaction with the region connector element, to the final success page. This also includes error cases resulting from the user, a region connector, or a PA's shortcomings.

**Why**
Having the full user flow defined helps the design and implementation of the EDDIE button as a multistep form. It also doubles as documentation for the permission facade and can be used to define functional and user experience requirements for the EDDIE button and region connector elements.

**Scope**
The documentation should ideally include all possible edge and error cases. This includes errors produced by any party that interacts with EDDIE, as well as the framework itself. We also want to define the user flow for all our region connector elements.

**Result**
The results should be added to our documentation and be readily available for developers of the EDDIE button and region connectors.
```[tasklist]
### Tasks
- [x] Define the happy path for a typical data need and region connector
- [x] Define error cases
- [x] Define user flows for all individual region connectors
- [x] Make the documentation available to our development team
- [x] Discuss and evaluate the user flow internally
```
