### ISSUE TITLE
Admin Console: Dashboard

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1298]
## Short Description

To quickly give an overview of the state and scale of an EDDIE instance, a dashboard is to be implemented that shows the most important key metrics at a glance.

The existing API allows for the following:
- Aggregate permissions from the status messages repository
- List DNs from the DN API and filter permissions on the client
- List RCs from RC Metadata API and filter permissions in repository

Additional APIs are to be implemented if needed to provide a feature defined in the dashboard design.

## Acceptance Criteria

- [ ] Implements the Figma design
- [ ] Shows permission statistics
- [ ] Shows data needs overview with statistics
- [ ] Shows region connectors overview with permission statistics
- [ ] Shows region connector status on a map for visual reference (mostly motivated by demonstrative purposes)
- [ ] Shows distribution of permissions per region connector

## Design/UI/UX Requirements

<img width="3456" height="2844" alt="Image" src="https://github.com/user-attachments/assets/15e0cde5-3563-4e84-a5fa-16bb3cfa2458" />

<img width="3456" height="2844" alt="Image" src="https://github.com/user-attachments/assets/9525d284-9bad-471f-82b1-ee6997edeed4" />

## Tasks
- [x] https://github.com/eddie-energy/eddie/issues/1485
- [x] https://github.com/eddie-energy/eddie/issues/1467
- [x] https://github.com/eddie-energy/eddie/issues/1469
- [x] https://github.com/eddie-energy/eddie/issues/1471
- [ ] SVG map of region connectors similar to https://explorer.missiondata.io
