### ISSUE TITLE
Describe deployment strategy for Eddie via K8s

### ISSUE THREAD

**Issue by fweingartshofer** [eddie-energy/eddie#1311]
## Short Description
Currently, there are many different ways to deploy eddie, via docker compose or just Java.
We need a strategy on how to deploy it via k8s for hardening stages and partners

### Tasks
- [x] https://github.com/eddie-energy/eddie/issues/1305
- [x] https://github.com/eddie-energy/eddie/issues/1058
- [x] https://github.com/eddie-energy/eddie/issues/1252
- [x] https://github.com/eddie-energy/eddie/issues/1361

## Design/UI/UX Requirements _(optional)_
_Please specify this if a specific design or user interface (flow) is desired.
Ideally this section consists of annotated mockups._
