### ISSUE TITLE
Admin Console: Permissions View

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1392]
## Short Description

The permissions view allows the eligible party to look up and terminate existing permissions.
Replaces the initial version of the admin console implemented with #938.

## Acceptance Criteria
- [x] Ability to search and filter permissions
- [ ] Terminate permissions one by one or in bulk
- [x] Permissions show timeline of status change
- [ ] Permission status changes include additional information (error messages) provided with the status change

### Dark mode

<img width="2097" height="656" alt="Image" src="https://github.com/user-attachments/assets/b42413cb-3fa9-4334-9ea0-9218b3d6c25d" />

**Extended permission status view**

<img width="2814" height="1148" alt="Image" src="https://github.com/user-attachments/assets/fae20952-b811-47c2-b4f7-7c1feca9795a" />

### Light mode

<img width="2097" height="656" alt="Image" src="https://github.com/user-attachments/assets/10160c4d-ee4b-4819-bcbe-4744d3220641" />

**Extended permission status view**

<img width="2814" height="1148" alt="Image" src="https://github.com/user-attachments/assets/f42fec4f-71f3-46fd-ae3e-36cf9519341c" />

## Considered Use-Case

A typical use-case would be an issue reported by a customer where the request was created, but no data is available in the eligible party application. The eligible party might look up the permission for that user and timeframe and find a timeline of changes that led to the current state. They might also want to display all permissions that failed with the same status in a similar timeframe to find a pattern or underlying issue.

## Permission States

For an overview, permission states can be categorized into four categories: Processing, Active, Inactive, and Failed. Permissions in the failed state are likely to be caused by a misconfiguration, making them particularly important for the eligible party.

![admin-console-states drawio](https://github.com/user-attachments/assets/45ae79d0-3e8f-40e4-9ec4-1c6c8ad0ba83)

## Tasks
- [x] Redesign the permissions view for many permissions
