### ISSUE TITLE
Admin Console: Region Connectors View

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1393]
## Short Description

The goal is to allow the eligible party to configure region connectors in a guided dialog. This includes the configuration of properties, uploading of certificates, entering of secrets, references to documentation, ...

In addition to the information found on the dashboard, this page should also inform about the availability, supported features, configuration and usage metrics of configured region connectors.

## Acceptance Criteria
- [ ] Lists all implemented region connectors
- [ ] Shows region connector status (configured/available)
- [ ] Shows supported features
- [ ] Shows [data need rules](#1246) to indicate supported data needs
- [ ] Shows configuration with redacted secrets
- [ ] Shows region connector metadata
- [ ] Links onboarding documentation

## Design/UI/UX Requirements

<img width="1236" height="410" alt="Image" src="https://github.com/user-attachments/assets/732b9291-af4f-45e9-adf8-886605df11b7" />

<img width="2814" height="1627" alt="Image" src="https://github.com/user-attachments/assets/3f93a209-65f9-4e9c-92e6-d99fc68c9fbe" />

<img width="1236" height="410" alt="Image" src="https://github.com/user-attachments/assets/325ed8f1-bdeb-4925-a98d-9bc12b2d7451" />

<img width="2814" height="1627" alt="Image" src="https://github.com/user-attachments/assets/70f98f18-35b8-4d5d-8cea-b69dab91bb5c" />

## Tasks
- [x] https://github.com/eddie-energy/eddie/issues/1492
- [x] #1356
- [x] #1354
- [x] https://github.com/eddie-energy/eddie/issues/1472
- [x] Link to onboarding information for region connectors
