### ISSUE TITLE
Epic (T3.3): EDDIE Administrative Console

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1395]
This ticket aims to track all tasks related to the implementation of the administrative console as envisioned in the Grant Agreement.

***From the Grant Agreement:***

> This task implements the administrative console as described in the methodology section containing the following areas
> - Authentication and authorization of users acting on behalf of the eligible party (EP)
> - Management of MS connection/onboarding information
> - Management of data-driven services
> - Management consents and their statuses
> - Logging, debugging and analyses
> - Dashboard visualizing statistics on the usage of the EDDIE Framework based on an opt-in feature for framework users.
> - Push notification mechanisms (e.g., email, cell phone) for EPs of important events
>
> Apart from the raw functionality of the administrative console, automated unit, integration and UI tests will be delivered, as well as automated deployment scripts. A “test first” approach shall be used in development and maintenance – all these artifacts will be released to the open-source platform and the continuous integration chain.

Diagrams and other documentation that is not present in the repository are located on [Sharepoint](https://hartnerconsultingcom.sharepoint.com/:f:/r/sites/EuropeanDataAccess/Freigegebene%20Dokumente/WPs/WP3_DataAccessComponents/Admin%20Console?csf=1&web=1&e=9Ck3Xo).
A high-fidelity design is available on [Figma](https://www.figma.com/design/KKHDSHrFkyCD5UAV4DSKTL/Admin-Console?node-id=0-1&t=JlUYokq5Xk4iSfZy-1).

The application is organized into multiple views, which initial implementations are tracked by separate requirement tickets.

### Views
- [ ] #1298
- [ ] #1392
- [ ] #1393
- [ ] https://github.com/eddie-energy/eddie/issues/1465
- [ ] https://github.com/eddie-energy/eddie/issues/1474

### Operational
- [x] https://github.com/eddie-energy/eddie/issues/1451
- [x] https://github.com/eddie-energy/eddie/issues/1466
- [x] https://github.com/eddie-energy/eddie/issues/1596
- [ ] Configure admin console domain for CORS protection
- [x] #246
- [x] Use colors from EDDIE website and logo in admin console where possible
- [ ] #1713 

### Planned Features
- [ ] Generate test data for development
- [ ] 2FA Authentication
- [ ] Push Notifications for important events (which events?)
- [ ] Highlight error cases (exceptions) found by the system monitoring tool on an exceptions page

This ticket effectively replaces #199 and most of its child tasks.

## Admin Console ≠ System Monitor

While the administrative console should inform about the general system state, including the availability of region connectors and statistics on permissions, the administrative console is not developed as a system monitoring tool. Monitoring tasks like log aggregation, exception management, and performance monitoring are highly complex and best solved by using a specialized software.

An initial discussion can be found in #774.
