### ISSUE TITLE
Admin Console: Data Needs Management

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1465]
## Short Description

In addition to the information found on the dashboard, this page displays available data needs with statistics about permissions created for them.

The [data needs management API](https://github.com/eddie-energy/eddie/blob/main/data-needs/data-needs-management-api.http) provides endpoints for CRUD operations.
Information on data need calculations and supported region connectors are sourced from the [core APIs](https://github.com/eddie-energy/eddie/blob/main/core/api.http).

## Acceptance Criteria
- [ ] Individual data needs can be enabled/disabled
- [ ] Data needs can be filtered by name and type
- [ ] Data needs can be deleted, and the user is informed about the consequences of that action
- [ ] Data needs show which region connectors support them and which do not
- [ ] A working EDDIE button configured with the data need is rendered in addition to example code for it

## Design/UI/UX Requirements

<img width="3456" height="2160" alt="Image" src="https://github.com/user-attachments/assets/5247d670-901e-4819-925b-00a36f373919" />

### Creation of an Accounting Point Data Need

<img width="1796" height="1068" alt="Image" src="https://github.com/user-attachments/assets/92697a46-975d-4a81-ab8c-284908a74f6e" />

### Creation of a Validated Historical Data Data Need

<img width="1796" height="1702" alt="Image" src="https://github.com/user-attachments/assets/18531ae9-b89e-49d2-a65d-921af1a336ba" />

### Creation of an AIIDA Data Need

<img width="1796" height="1518" alt="Image" src="https://github.com/user-attachments/assets/05943b5d-237d-402a-84bd-8daf2fbcaf67" />

## Tasks
- [x] Display configured data needs
- [x] https://github.com/eddie-energy/eddie/issues/1467
- [ ] Display supported region connectors per data need
- [x] Add, disable, and delete data needs (using the data needs API)
