### ISSUE TITLE
Define EDDIE UI Design Tokens (Colors, Fonts)

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1473]
## Short Description

Define EDDIE colors to be used consistently.
Reuse from EDDIE website and [Corporate Design](https://hartnerconsultingcom.sharepoint.com/sites/EuropeanDataAccess/Freigegebene%20Dokumente/Forms/AllItems.aspx?id=%2Fsites%2FEuropeanDataAccess%2FFreigegebene%20Dokumente%2FWPs%2FWP9_Communication%2FTemplates%2FEDDIE_CD&viewid=124bd1ff-30ba-45d5-8b45-c4da5097508a), or request new ones from Formfroh.

For EDDIE Button, AIIDA UI, Admin Console.

Align with EDDIE Logo and Website.

Sync with Marketplace?

## Acceptance Criteria
- [ ] It is clear which design tokens to use for each application
- [ ] Colors support dark and light mode
- [ ] Colors follow WCAG
- [ ] Tokens work for web and mobile applications
- [ ] Applications have no need to define additional colors

## Tasks
- [ ] Use colors from EDDIE website and logo in admin console where possible
- [ ] Use colors from EDDIE website and logo in the EDDIE button where possible
- [ ] Sync with Formfroh on colors and other design guideliens for frontend applications
- [ ] Add repo or module that exports design tokens to our projects (CSS, JS)
