### ISSUE TITLE
Admin Console: Framework Configuration

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#1474]
## Short Description

A separate view should allow the user to display the current configuration of the EDDIE framework. This includes all environment variables / properties found in the [framework documentation](https://eddie-web.projekte.fh-hagenberg.at/framework/1-running/OPERATION.html#configuration).

This view is only intended for reading. It is currently not possible to adjust configuration at run-time, since almost all changes require a restart of the EDDIE framework. Restarts also depend on the environment of the deployment. It might be feasible to allow some configuration to be changed at run-time, or allow users to restart the framework JAR from the admin UI.

The page should only display configurations that can be adapted by the EP (which excludes Spring properties) and should not show any secrets and tokens.

## Acceptance Criteria
- [ ] EDDIE Framework configuration properties are listed as key-value pairs
- [ ] Sensitive information is redacted (ideally on the server-side)

## Design/UI/UX Requirements

This view currently does not have a standalone design.
We can create one if needed.
Properties are to be listed in a tabular layout similar to the one found in the region connectors view.
It should also link to the framework documentation.

<img width="1136" height="1038" alt="Image" src="https://github.com/user-attachments/assets/4ce3e6ef-b329-4de6-8d19-a4380c865f99" />

## Considered Use-Case

The main use-case of this page in its read-only state is to check configuration without having to view the source code, and for users to find and append their configurations when reporting issues to the framework operator or EDDIE team.

Its long-term use is to allow basic configuration from within the admin console.

## Tasks
- [ ] Quickly draft static html of what it could look like (ChatGPT on docs)
- [ ] Link framework operation / configuration documentation
- [ ] Add endpoints to query configuration parameters (need to figure out how first)
- [ ] Display core configuration
- [ ] Display configurations per region connector in separate sections (check if we want to show this in both RC and config view or just one)
