### ISSUE TITLE
Epic: Region Connector Architecture

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#157]
**What**

This epic is used to group tasks to define the region connector architecture, applying the learnings of MVP1 development.

Most tasks will be done in a meeting with the whole team (@eddie-energy/fh-dev).
 
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/176
- [ ] https://github.com/eddie-energy/eddie/issues/108
- [ ] https://github.com/eddie-energy/eddie/issues/109
- [ ] https://github.com/eddie-energy/eddie/issues/113
- [ ] https://github.com/eddie-energy/eddie/issues/118
- [ ] https://github.com/eddie-energy/eddie/issues/122
- [ ] https://github.com/eddie-energy/eddie/issues/172
- [ ] https://github.com/eddie-energy/eddie/issues/177
- [ ] https://github.com/eddie-energy/eddie/issues/178
- [ ] https://github.com/eddie-energy/eddie/issues/287
