### ISSUE TITLE
Epic: RC-AT-EDA

### ISSUE THREAD

**Issue by blazing-panda** [eddie-energy/eddie#18]
# Overview
Epic for the Region Connector for EDA in Austria (i.e. all Austrian DSOs).

## Intended outcome
The goal of this task is to create the region connector to integrate HVD from Austrian DSOs into EDDIE

## State in Austria

In Austria the MDA (Meter Data Administrator) role is done by the DSO (Distribution System Operator).
There are 139 different DSOs but data exchange is standardized by [EDA](https://www.ebutilities.at/home.html) (energie wirtschaftlicher datenaustausch) and works by exchanging XML data files with decentralized instances of the [Ponton XP Messenger](https://www.ponton.de/products/xpmessenger/).
Permission requests/answers as well as actual consumption data is exchanged by these XMLs and workflows can be found [here](https://www.ebutilities.at/utilities/prozesse/).
Especially important for us is the [CCMO](https://www.ebutilities.at/utilities/prozesse/detail.php?ProcessID=321&ReturnTo=%2Futilities%2Fprozesse%2F) (Consent Management - Online Datenfreigabe).
The region connector will need to be able to send/receive & process these standardized XMLs, i.e. need to provide the same functionality as the Ponton XP Messenger.

## TODO
```[tasklist]
### RC-AT-EDA
- [ ] https://github.com/eddie-energy/eddie/issues/33
- [ ] https://github.com/eddie-energy/eddie/issues/35
- [ ] https://github.com/eddie-energy/eddie/issues/37
- [ ] https://github.com/eddie-energy/eddie/issues/38
- [ ] https://github.com/eddie-energy/eddie/issues/7
- [ ] https://github.com/eddie-energy/eddie/issues/46
- [ ] https://github.com/eddie-energy/eddie/issues/54
- [ ] https://github.com/eddie-energy/eddie/issues/75
- [ ] https://github.com/eddie-energy/eddie/issues/76
- [ ] https://github.com/eddie-energy/eddie/issues/77
- [ ] https://github.com/eddie-energy/eddie/issues/96
```

### Integration
For MVP1 we get access to a Ponton Messenger instance for a test & production environment and don't need to concern ourselves with exchanging the XML files.
We need to implement the [CCMO](https://www.ebutilities.at/utilities/prozesse/detail.php?ProcessID=321&ReturnTo=%2Futilities%2Fprozesse%2F) workflow.
We will use the Java API for the messenger ([documentation](https://www.ponton.de/products/xpmessenger/xp-documentation/))

### Current State

Currently communication with EDA is done via hotfolders hosted on @georghartner's private server.
There is another Windows VM run by EDA, on which a Ponton XP messenger monitors hotfolders as well.
The contents of the hotfolders from @georghartner's server are automatically mirrored to the VM's folder by a Python script running on the VM.
To get started faster, we have direct access to @georghartner's server via SSH, but @georghartner's would prefer that we host another server where he mirrors the hotfolders.
The hotfolders can be mirror to the local computer with e.g. rsync.

To send a message to e.g. NetzOÖ, a correct XML message needs to be placed in the outbound folder on @georghartner's server, sending then happens without further action.
Incoming messenges (e.g. consumption records from NetzOÖ) are placed in the inbound folder on @georghartner's server.
There is also a failed folder.

### Permission workflow

To request permission, we need to implement the workflow defined [here](https://www.ebutilities.at/utilities/prozesse/detail.php?ProcessID=321).

Short summary of the steps:
1. Create a Customer Consent Management Online Request (CCMO). This contains information about the elligible party, the metering point we want the data of (customer) and what kind of data we are requesting (HVD)
2. The CCMO Request needs to be approved by the customer via the MDA Portal (DSO in the case of austria).
3. If the customer accepts, we should receive the metering data in the form of consumption records (can be found in the process documentation).
