### ISSUE TITLE
Introduce "DataNeeds" (former "Services") into the EDDIE framework as needed by EDDIE online

### ISSUE THREAD

**Issue by h-carl** [eddie-energy/eddie#194]
Possible solution to introduce data needs:
- data needs are provided to the framework via the spring environment (first static, then in a dynamic way)
- a rest-API is provided by the framework to provide data needs details to the popup window, e.g. GET eddie.online/api/data-need/historical-3m
- The data-need is provided by the EP application to the EDDIE Popup (Custom Element attribute)
- The EDDIE popup queries the data-need and preconfigures and locks it's values

The usage of Spring along with this new function might be a bit challenging but is surely the more sustainable way to go.

### Addition
The main problems are already solved in the dev branch https://github.com/eddie-energy/eddie/tree/194-include-data-needs The following features are already implemented:
- a data need id can be provided to the eddie connect button as a HTML attribute
- data needs are read from their own config file that is processed by Spring config
- a REST API for querying those data need attributes by their id is realized via Spring MVC
- that information is fetched by the permission popup and propagated to the PA specific frontend modules
```[tasklist]
### Tasks
- [x] write sufficient unit tests
- [x] check remaining warnings etc.
- [x] document data-need config
```
