### ISSUE TITLE
EDDIE Admin Console

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#199]
### Source:
- Grant Agreement - Definition of the Actions (Part A) - page 10
- Grant Agreement - Definition of the Actions (Part B) - page 13, 17

### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/236
- [ ] Probably use pre-designed template for ADMIN UIs
- [ ] https://github.com/eddie-energy/eddie/issues/235
- [ ] Management of onboarding and configuration data for region connectors, make it possible to activate/deactivate these region connectors
- [ ] https://github.com/eddie-energy/eddie/issues/238
- [ ] https://github.com/eddie-energy/eddie/issues/237
- [x] https://github.com/eddie-energy/eddie/issues/240
- [x] Show and make manageable consent processes and their states
- [x] Establish the option to "terminate" a consent from the admin console
- [x] https://github.com/eddie-energy/eddie/issues/239
- [x] foresee proper Region connector setup pages with extensive documentation options and tutorials for how to connect in which MS
- [ ] Allow for change of passwords and 2FA
- [ ] Create "Exceptions Page", where exceptions from run-through processes are automatically displayed and from where corrective actions can be triggered (in a later stage)
