### ISSUE TITLE
SGE Connection with Enedis

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#200]
FlexiDAO raised that it is an issue that for their bigger commercial and industrial clients, they can't get the data from DataConnect, but they must go through the SGE portal. Clarify what needs to be done to connect all Enedis data.

### Tasks
- [x] contact Enedis (probably Remy) for how to connect to SG and if this is absolutely necessary
- [x] Contact Eloi's team at FlexiDAO for help
- [x] INFO FROM ENEDIS: https://datahub-enedis.fr/fournisseurs-de-services/sge-tiers/
- [ ] Find a test partner (e.g. through Enedis or through Laurent) that we can use to connect to SGE data
- [x] Find out and make an overview about which data is only available from DataConnect and which from Linky/DataConnect
- [x] Find out whats needed to connect
- [ ] According to this table https://datahub-enedis.fr/fournisseurs-de-services/sge-tiers/les-services-de-donnees/ it might also be that data must be gathered through SFT or SMTP
