### ISSUE TITLE
AIIDA: End-to-end workflow realisation

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#203]
### Tasks
- [x] Extend the EDDIE Framework to show an end-to-end integration with AIIDA
- [x] Provide an AIIDA service that provides at least dummy realtime data
- [x] Extend the popoup with a data family P1 data, showing the "Finder QR code"
- [x] Implement AIIDA<>EDDIE Framework consent establishment process as specified in https://github.com/georghartner/eddie/wiki/AIIDA-Sequence-Diagrams
- [x] Also integrate termination and revocation of consent as specified here: https://github.com/georghartner/eddie/wiki/EDDIE-Consent-Facade-Specification
- [ ] Extend EDDIE Admin Console if needed
- [ ] Don't forget to also make available a "consent establishment lollipop service" as specified in the bottom section of this page: https://github.com/georghartner/eddie/wiki/Vienna,-Nov-14th-15th-2022---ENT,FHO,VIE,AIT---University-of-Vienna,-Faculty-of-Computer-Science,-W%C3%A4hringerstra%C3%9Fe-29,-1090-Wien
