### ISSUE TITLE
Redesign EDDIE Permission Popup

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#204]
**Description:**
Final customers should not be required to specify the data they share themselves. This should be coming from the service descriptor in the backend.

**Requirements:**

```[tasklist]
### Tasks
- [x] Harmonize look and feel across region connectors
- [x] Extract start and end date fields from region connectors and prepare to allow the eligible party to configure defaults.
- [x] Add descriptions with explanations to fields specific to a region connector
- [ ] https://github.com/eddie-energy/eddie/issues/273
- [x] Evaluate showing distribution system operators (DSO) that are not supported by EDDIE.
- [x] Indicate to the user the type of data (standardized data family) requested by the eligible party. As of now, this includes Validated Historical Consumption Data (VHCD) from the past, VHCD from the future, and AIIDA P1 Real-time data. Prepare for this to be configurable.
- [x] Display a summary of which data is requested (familiy, timespan) on top of the pop-up.
- [x] Link to the website of the permission administrator and add instructions on how to continue after interacting with the pop-up.
- [ ] https://github.com/eddie-energy/eddie/issues/202
- [x] Indicate the status of the permission request and which steps are required by the user (e.g. "please complete the process in PA portal").
- [x] Optimize the pop-up for mobile. Currently, region connector elements are not working correctly.
- [x] Avoid opening a new page for the callback URL by Enedis.
- [ ] https://github.com/eddie-energy/eddie/issues/291
```

**Acceptance criteria:** Requirements have been implemented, and the results were approved by the team.

**Estimation:** 13h

**Blockers:** None

**Source:** Georg (refined by Markus)
