### ISSUE TITLE
Epic (T2.4):  Scripted deployment configurations and EDDIE framework documentation

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#217]
This epic refers to the continous integration, delivery and deployment of dedicated components of the EDDIE framework.
```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/218
- [ ] https://github.com/eddie-energy/eddie/issues/220
- [ ] https://github.com/eddie-energy/eddie/issues/219
- [ ] https://github.com/eddie-energy/eddie/issues/221
- [ ] https://github.com/eddie-energy/eddie/issues/222
- [ ] https://github.com/eddie-energy/eddie/issues/223
- [ ] https://github.com/eddie-energy/eddie/issues/224
- [ ] https://github.com/eddie-energy/eddie/issues/225
```
