### ISSUE TITLE
Epic (T3.1): EDDIE Consent Facade

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#226]
This task focuses on a streamlined user flow that leads customers to their consent administrator by providing an integrated interface. This interface communicates with the EDDIE Framework communication layer (delivered by WP4) via predefined and unified data formats. Consent and the underlying process needs to be described on a conceptual level in order to be able to define the corresponding interface/façade since different regions have different understandings of consent. Outcomes of this task will be integrated in the EDDIE Framework constituting the baseline for the reference process implementation in T3.2. Additionally, the consent information and resulting data structure is inherently important including consent status, additional consent conditions (e.g., start, expiration, limiting factors, data restrictions). 

**Source:** Grant Agreement - Definition of the Action (Part A): page 9

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/204
- [ ] https://github.com/eddie-energy/eddie/issues/227
- [ ] https://github.com/eddie-energy/eddie/issues/228
- [ ] https://github.com/eddie-energy/eddie/issues/229
- [ ] https://github.com/eddie-energy/eddie/issues/230
```
