### ISSUE TITLE
Epic (T3.2): Reference process implementation

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#231]
**Source:** Grant Agreement - Definition of the Action - page 9
```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/232
- [ ] https://github.com/eddie-energy/eddie/issues/233
- [ ] https://github.com/eddie-energy/eddie/issues/181
- [ ] https://github.com/eddie-energy/eddie/issues/282
- [ ] https://github.com/eddie-energy/eddie/issues/287
- [ ] https://github.com/eddie-energy/eddie/issues/177
- [ ] https://github.com/eddie-energy/eddie/issues/295
- [ ] https://github.com/eddie-energy/eddie/issues/296
- [ ] #304
```
