### ISSUE TITLE
Epic (T3.4): EDDIE Administrative Interface for in-house Data Access

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#241]
**Source:** 
- Grant Agreement - Definition of the Actions (Part A) - p. 10
- Grant Agreement - Definition of the Actions (Part B) - p. 18

### Tasks
- [x] https://github.com/eddie-energy/eddie/issues/242
- [x] https://github.com/eddie-energy/eddie/issues/243
- [x] https://github.com/eddie-energy/eddie/issues/244
- [x] https://github.com/eddie-energy/eddie/issues/245
- [x] AIIDA - Cloud connection
- [x] https://github.com/eddie-energy/eddie/issues/815
- [x] https://github.com/eddie-energy/eddie/issues/835
- [x] https://github.com/eddie-energy/eddie/issues/834
