### ISSUE TITLE
Epic (T5.2): EU consortium participants region connectors

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#247]
A region connector for each of the following five EU member states shall be implemented: Austria (EDA), Denmark (Energinet), France (ENEDIS, D4G), Germany (ETP), Italy (SEV) and Spain (Datadis).

### Requirements:
**D5.3 - Region connectors implemented**
Source: Grant Agreement - Definition of the Action (Part A) - p.25

- At least seven EU member state connectors, the ElectraLink (UK) and the Green Button (US) connector are implemented.
- Onboarding instructions are provided
- reference process and permission facade plugin is provided
- secure identification is provided
- consent processes are provided
- plugins for regionally used meter (operation) models and reference data is provided

### Tasks
- [x] https://github.com/eddie-energy/eddie/issues/263
- [x] https://github.com/eddie-energy/eddie/issues/201
- [x] https://github.com/eddie-energy/eddie/issues/264
- [x] https://github.com/eddie-energy/eddie/issues/49
- [x] Germany (ETP)
- [ ] Italy

**Comment by sgrue** [comment]
A first German Region Connector has been implemented by ETA+ (https://github.com/eddie-energy/eddie/issues/2186).
