### ISSUE TITLE
Enable AccountingPointData access (for EDA and Enedis in a first step)

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#266]
**Source:**
Georg Hartner

```[tasklist]
### Tasks
- [ ] Take EDA as a template and create CIM target schema for master data exchange. Take https://hartnerconsultingcom.sharepoint.com/:w:/s/EuropeanDataAccess/EVyRDoVNftpNqnw0oovLihUB8VdwJc8OQhA3MVOcJm9enw?e=eYoQXm as a start (ignore party master data for now).
- [ ] Adapt Consent popup to show a Data Family "Accounting point master data"
- [ ] No need to show an end date. Just a master data date for when the master data is applicable.
- [ ] No need for "future master data" for now.
- [ ] No need for "Termination or Revocation" (for now)
- [x] Implement for EDA as a first step
- [ ] Implement for Enedis as a second step
- [ ] Ensure that the data family can be assigned to a "service
```
