### ISSUE TITLE
Allow applications to react to user interactions and permission status changes with JavaScript Hooks and/or Redirect Page(s)

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#268]
Data-driven applications need to be able to react to status changes to, for example, forward in the onboarding procedure, redirect to rejection pages, or just show the recently received data.

This is to be achieved by
- propagating DOM events
- adding attributes that take functions to run on such events
- adding attributes that take locations to redirect to on user interactions

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/564
- [ ] https://github.com/eddie-energy/eddie/issues/1030
- [ ] https://github.com/eddie-energy/eddie/issues/1180
```
