### ISSUE TITLE
Schema-bind Kafka topics to CIM-Model

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#269]
```[tasklist]
### Tasks
- [x] Ensure that all data pushed through the Kafka topics towards the services and from services back to EDDIE Framework are schema-bound
- [ ] https://github.com/eddie-energy/eddie/issues/334
- [ ] #344
- [x] Make data exchange on “status messages” Kafka topics CIM-compliant
```
