### ISSUE TITLE
Support Estonia Elering Data Hub / Estfeed as region connector

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#279]
Contact georg.hartner@eddie.energy and Colin Broderick for test accounts and documentation.

Info we have on Estonia:

Website: Estonian TSO https://elering.ee/
Contact: ask Georg
EIC: 10X1001A1001A39W (should be used as sender for MPA/MDA)

Data Hub: https://estfeed.elering.ee/

Access Documentation: https://elering.ee/sites/default/files/2022-05/%281%29%20Estfeed%20ELECTRICITY%20DATAHUB%20Users%2C%20functionality%20and%20access%20rights_EN_C.docx

We use TARA application for authorization, which is provided by Republic of Estonia Information System Authority, but Elering stores identities in an internal service.

Eligible party onboarding:
Suppliers:
1) Supplier submits economic activity notice regarding electricity sales to national registry
2) Supplier contacts Elering with the intention to start electricity supply and provides necessary details for Datahub (DH) usage agreement
3) Elering prepares the agreement and the agreement is signed by both parties
4) Elering defines the supplier in DH enabling access to suppliers' functionalities - supplier is able to use the API integration or use web interface
Aggregators:
1) Aggregator concludes balancing service provider agreement with Elering
2) Aggregator concludes GH usage agreemtn with Elering
3) Elering defines the aggregator in DH enabling access to aggregators' functionalities - aggregator is able to use the API integration or use web interface
Energy service providers:
1) Send a request in free form to estfeed@elering.ee
2) Questionnaire to check if potential eligible party follows GDPR rules in their operations
3) Signing DH usage agreement with terms of service and we set a purpose for the eligible party (if needed then multiple purposes will be set)
4) Technical integration 
5) Go live

**Tasks:**
- [ ] EE: Future data can be requested from now to X days/months in the future.
- [ ] EE: Future data can be received and provided.
- [ ] EE: Users can accept or decline data requests
