### ISSUE TITLE
Describe and implement data needs into the EDDIE Framework

### ISSUE THREAD

**Issue by h-carl** [eddie-energy/eddie#305]
The _connect_ button of the EDDIE framework needs to be preconfigured with a data need that specifies the type and quality of data needed by the eligible party's application. In the Grant Agreement, this concept was called **Service**.

Motivation for the inclusion of this concept is, that an eligible party application can usually only work properly, if matching data is supplied. E.g. an application needing near realtime consumption data won't properly work if the user requests historical validated consumption data with only one measurement a day.
```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/193
- [ ] https://github.com/eddie-energy/eddie/issues/194
- [ ] https://github.com/eddie-energy/eddie/issues/291
- [ ] https://github.com/eddie-energy/eddie/issues/306
- [ ] https://github.com/eddie-energy/eddie/issues/307
- [ ] https://github.com/eddie-energy/eddie/issues/308
- [ ] https://github.com/eddie-energy/eddie/issues/309
- [ ] https://github.com/eddie-energy/eddie/issues/341
- [ ] https://github.com/eddie-energy/eddie/issues/344
```
