### ISSUE TITLE
Make data exchange on  “consumption-records” Kafka topics CIM-compliant

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#352]
**What**
As a first step the data format of consumption records that are sent via Kafka must be CIM compliant. 

The following graphics illustrates the CIM mapping for Austria:

![Image](https://github.com/eddie-energy/eddie/assets/42996364/05d2ab12-399f-4bbe-b579-f500b3026387)

The current available XSD schema can be downloaded here:
[ValidatedHistoricalData_MarketDocument_2023-06-23T09.04.26.xsd](https://hartnerconsultingcom.sharepoint.com/:u:/r/sites/EuropeanDataAccess/Freigegebene%20Dokumente/Meetings/Development%20and%20Architecture/Documentation%20Repository/ValidatedHistoricalData_MarketDocument_2023-06-23T09.04.26.xsd?csf=1&web=1&e=daa4Mo)

Latest (V0.82) generated Java Classes from Wout can be downloaded here:
[VHD_v0.82 Java.zip](https://github.com/eddie-energy/eddie/files/13066662/VHD_v0.82.Java.zip)

**Why**
Requested to demonstration purposes on eddie.online for the ENLIT event.

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/397
- [ ] https://github.com/eddie-energy/eddie/issues/396
- [ ] https://github.com/eddie-energy/eddie/issues/398
- [ ] https://github.com/eddie-energy/eddie/issues/399
- [ ] https://github.com/eddie-energy/eddie/issues/400
- [ ] https://github.com/eddie-energy/eddie/issues/404
- [ ] https://github.com/eddie-energy/eddie/issues/401
- [ ] https://github.com/eddie-energy/eddie/issues/402
```
