### ISSUE TITLE
Endpoint for verifying that region connector supports the given dataneed

### ISSUE THREAD

**Issue by blazing-panda** [eddie-energy/eddie#373]
RegionConnectors should provide an Endpoint that varifies wether or not a given DataNeed is supported.
E.g checking if it can provide the required data `Granularity`

The frontend should then be able to display to the end user, that the DataNeed is not supported by their RegionConnector

In addition to returning whether a certain RC supports a data need or not, the actual start and end times for a permission request should be returned as well. E.g. for open start, the RC calculates the start date and the data needs API cannot return the actual start date. This information can then be displayed to the customer in the popup (another ticket).
```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/998
- [ ] https://github.com/eddie-energy/eddie/issues/1008
- [ ] https://github.com/eddie-energy/eddie/issues/1018
- [ ] https://github.com/eddie-energy/eddie/issues/1022
- [ ] https://github.com/eddie-energy/eddie/issues/1031
- [ ] https://github.com/eddie-energy/eddie/issues/1025
```

## Acceptance Criteria
  - [x] *Actual* data start & end date
  - [x] *Actual* permission start & end date
  - [x] possible Granularity 
  - [x] *Any other information, that seems sensible*
