### ISSUE TITLE
Implement REVOKE permission for all region connectors

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#395]
Revocation of the permission by the final customer (as of implementing regulations). Revokations might happen explicitly (e.g. by a user logging in to a DSO portal and clicking a button) or implicitly (e.g. when a customer moves out and loses its entitlement to a meteringpoint). From each region-connector, it must be possible to receive the information if the final customer has revoked its consent. In AT, we will simply get a market message, in REST-based environments we sometimes need to poll.

In either way, the respective response must be fed back to the eligible party as a standardised CIM message, so please ensure to link up with the CIM Czar, Wout and Laurent. Also, ensure that after a permission has been revoked, no "future consumption data" are being polled.
```[tasklist]
### Tasks
- [ ] Implement reaction to REVOKE in AT
- [ ] Implement reaction to REVOKE in DK
- [ ] Implement reaction to REVOKE in FR
- [ ] Implement reaction to REVOKE in ES
```
