### ISSUE TITLE
Epic: RC-GENERAL

### ISSUE THREAD

**Issue by fweingartshofer** [eddie-energy/eddie#50]
```[tasklist]
- [ ] https://github.com/eddie-energy/eddie/issues/36
- [ ] https://github.com/eddie-energy/eddie/issues/43
- [ ] https://github.com/eddie-energy/eddie/issues/39
```
