### ISSUE TITLE
Create a FULFILLED State for ALL Connections

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#575]
Situation now

Currently, all Connections stay in Status ACCEPTED, if they are accepted. However, we don't have a marker to indicate that we consider all data transfer done (if not TERMINATED or REVOKED). Hence, for all Connections (AIIDA as well as Historical Validated Consumption Data as well as for Future Validated Consumption Data as well as for Accounting Point Master Data), we should please indicate, that the purpose for the Connection is fulfilled. E.g. for:

- VHCD immediately after the data has been gathered
- VHCD future after the fetch time ends / all data has flown in
- Accounting Point Master Data after the data has been gathered
- AIIDA data after the permission time span ends

```[tasklist]
### Tasks
- [x] https://github.com/eddie-energy/eddie/issues/647
- [x] https://github.com/eddie-energy/eddie/issues/648
- [ ] https://github.com/eddie-energy/eddie/issues/644
- [ ] https://github.com/eddie-energy/eddie/issues/645
- [ ] https://github.com/eddie-energy/eddie/issues/646
```
