### ISSUE TITLE
Handle future data for AT, DK, ES, FR

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#582]
## Short Description
The region connectors AT, DK, ES and FR can handle the revocation (user triggered) and termination (supplier triggered) of future data permissions.

## Acceptance Criteria
- [x] Make it possible to request data from now to X days/months/years in the future
- [x] Once data becomes available (typically on the next day after delivery, but not always and it cant be pre-determined when exactly in time), gather the data and make it available through the usual channels just like the ones we use for historical data. Smart scheduling will be needed for REST-based APIs 
- [x] Make it possible to express a polling schedule (and intervals) for either DataNeed or region-connector
- [x] Once data has been gathered for the previous business day for a DataNeed, we should not poll anymore for that day
- [x] Revocation: User revokes a permission and further data is not accessible anymore.
- [x]  Termination: Supplier terminates a permission and further data is not accessible anymore.

## Design/UI/UX Requirements 
** No real design requirements

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/394
- [ ] https://github.com/eddie-energy/eddie/issues/395
- [ ] https://github.com/eddie-energy/eddie/issues/278
- [ ] https://github.com/eddie-energy/eddie/issues/339
- [ ] https://github.com/eddie-energy/eddie/issues/623
- [ ] https://github.com/eddie-energy/eddie/issues/628
- [ ] https://github.com/eddie-energy/eddie/issues/629
- [ ] https://github.com/eddie-energy/eddie/issues/630
- [ ] https://github.com/eddie-energy/eddie/issues/631
- [ ] https://github.com/eddie-energy/eddie/issues/645
- [ ] https://github.com/eddie-energy/eddie/issues/644
- [ ] https://github.com/eddie-energy/eddie/issues/648
- [ ] https://github.com/eddie-energy/eddie/issues/646
```
