### ISSUE TITLE
Create separate integration test system 

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#592]
## Short Description
An integration test system shall be created for exhaustive testing of the EDDIE framework (and AIIDA?), which is separated from EDDIE online (online.eddie.energy).

Please look at the indendet form of the acceptance tests as specified in: https://github.com/eddie-energy/x-eddie-online-e2e-tests

Final vision is to have a separate integration test environment where we can deploy and test new developments.

## Acceptance Criteria
- [x] Integration tests can be added and executed 
- [x] Integration tests can be executed automatically
- [x] get docker-compose.yml from Georg
- [x] deploy automatically the latest build with a tag eddie:integration, linked to a git branch
- [x] contact Georg do sync with eddieonline:forintegration as a user-facing infrastructure
- [x] have all available region connectors configured ready-to-be-used

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/615
```
