### ISSUE TITLE
Support CIM compliant VHCD documents

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#593]
## Short Description
VHCD (validated historical consumption data) are provided in form of CIM compliant documents.

IMPORTANT: Please chase Wout for the CIM mappings for Spain and Denmark

## Acceptance Criteria
- [ ] All region connectors provide VHCD as CIM compliant ValidatedHistoricalData_MarketDocuments

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/400
- [ ] https://github.com/eddie-energy/eddie/issues/399
- [ ] #396 
- [ ] #398 
```
