### ISSUE TITLE
Create a simple GUI to admin AIIDA

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#595]
## Short Description
AIIDA can be administrated via a simple GUI, which provides features for pasting the Base64 code, lists active/expired data needs and enables the termination of a permission.

## Acceptance Criteria
- [x] The Base64 code can be pasted.
- [x] Active data needs can be listed.
- [x] Expired data needs can be listed.
- [x] A permission can be terminated using a quick link.
- [x] It is containerized and can be deployed via Docker.
- [x] Communicate with wedl@formfroh.com to get a new Logo/probably figure for AIIDA, maybe also icon sets

## Design/UI/UX Requirements
- [ ] It would be good if you could already build it using a modern UI framework that can later be extended
- [ ] If possible, already add a user authentication area
- [ ] Interface should be styled in the EDDIE CD - see color/CD sheed in the EDDIE Online SharePoint (e.g. EDDIE_LogoSheet_DE.pdf): https://hartnerconsultingcom-my.sharepoint.com/personal/office_hartner-consulting_com//_layouts/15/onedrive.aspx?login_hint=office%40hartner%2Dconsulting%2Ecom&id=%2Fsites%2FEuropeanDataAccess%2FFreigegebene%20Dokumente%2FWPs%2FWP9%5FCommunication%2FTemplates&listurl=https%3A%2F%2Fhartnerconsultingcom%2Esharepoint%2Ecom%2Fsites%2FEuropeanDataAccess%2FFreigegebene%20Dokumente&remoteItem=%7B%22mp%22%3A%7B%22webAbsoluteUrl%22%3A%22https%3A%2F%2Fhartnerconsultingcom%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Foffice%5Fhartner%2Dconsulting%5Fcom%22%2C%22listFullUrl%22%3A%22https%3A%2F%2Fhartnerconsultingcom%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Foffice%5Fhartner%2Dconsulting%5Fcom%2FDocuments%22%2C%22rootFolder%22%3A%22%2Fpersonal%2Foffice%5Fhartner%2Dconsulting%5Fcom%2FDocuments%2FDocuments%20%2D%20European%20Data%20Access%22%7D%2C%22rsi%22%3A%7B%22listFullUrl%22%3A%22https%3A%2F%2Fhartnerconsultingcom%2Esharepoint%2Ecom%2Fsites%2FEuropeanDataAccess%2FFreigegebene%20Dokumente%22%2C%22rootFolder%22%3A%22%2Fsites%2FEuropeanDataAccess%2FFreigegebene%20Dokumente%2FWPs%2FWP9%5FCommunication%2FTemplates%22%2C%22webAbsoluteUrl%22%3A%22https%3A%2F%2Fhartnerconsultingcom%2Esharepoint%2Ecom%2Fsites%2FEuropeanDataAccess%22%7D%7D&view=0&viewid=124bd1ff%2D30ba%2D45d5%2D8b45%2Dc4da5097508a
```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/840
- [ ] https://github.com/eddie-energy/eddie/issues/894
- [ ] https://github.com/eddie-energy/eddie/issues/895
- [ ] #896
- [ ] https://github.com/eddie-energy/eddie/issues/897
```
