### ISSUE TITLE
Implement acceptance tests

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#596]
## Short Description
In the e2e tests project, 2 Smoke Tests have been specified. See: https://github.com/eddie-energy/x-eddie-online-e2e-tests/tree/main/test_descriptions

Also please check the available code, which should already cover a lot of the things needed for the automation of these scenarios. 

## Acceptance Criteria
- [x] Credentials etc. are outsourced to a property or env file that is not checked in to GitHub
- [x] The two test scenarios specified are implemented as runnable Playwright tests
- [x] The integration system is deployed and EDDIE Online Web, branch "integration" is linked with FHOOE Integration system
- [x] The two scenarios are run automatically on every check-in to the "integration" branch of EDDIE (after Container is build and deployed"

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/156
- [ ] https://github.com/eddie-energy/eddie/issues/662
- [ ] https://github.com/eddie-energy/eddie/issues/664
- [ ] https://github.com/eddie-energy/eddie/issues/1033
```
