### ISSUE TITLE
Support AccountingPointMasterData

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#603]
## Short Description
_Support AccountingPointMasterData for all region connectors._

## Acceptance Criteria
- [ ] _Data Type accounting point master data is selectable as a data need_
- [ ] _Process as described in the reference model is selectable ( see Annex of this document: https://hartnerconsultingcom.sharepoint.com/:w:/r/sites/EuropeanDataAccess/_layouts/15/Doc.aspx?sourcedoc=%7B850E915C-7E4D-4DDA-AA7C-34A28BCB8A15%7D&file=SGTF_IA_Phase2_Part3_MasterData_BasicMeteringPoint(4).docx&action=default&mobileredirect=true )_

## Design/UI/UX Requirements _(optional)_
_Adaptions in EDDIE Connect Popup to support this_

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/971
- [ ] https://github.com/eddie-energy/eddie/issues/1003
- [ ] https://github.com/eddie-energy/eddie/issues/1004
- [ ] https://github.com/eddie-energy/eddie/issues/1005
```
