### ISSUE TITLE
Refactor DataNeeds

### ISSUE THREAD

**Issue by blazing-panda** [eddie-energy/eddie#606]
## Short Description
The DataNeeds have to be refactored to consider newly gained information.
A big part is that DataNeeds have to support the necessary information needed by AIIDA (e.g. which data should be shared).
Among more things as mentioned in the linked tickets, the format of the start & end date (e.g., relative or absolute, end date inclusive or exclusive) should also be decided.

## Acceptance Criteria
- [ ] _first acceptance criteria_
- [ ] _second acceptance criteria_
- [ ] ...

## Design/UI/UX Requirements _(optional)_
_Please specify this if a specific design or user interface (flow) is desired.
Ideally this section consists of annotated mockups._

## Tasks that depend on / are blocked by this Requirement

- [ ] https://github.com/eddie-energy/eddie/issues/309
- [ ] https://github.com/eddie-energy/eddie/issues/341
- [ ] https://github.com/eddie-energy/eddie/issues/562
- [ ] https://github.com/eddie-energy/eddie/issues/373
- [ ] https://github.com/eddie-energy/eddie/issues/506
- [x] https://github.com/eddie-energy/eddie/issues/504
- [ ] https://github.com/eddie-energy/eddie/issues/474
- [ ] https://github.com/eddie-energy/eddie/issues/670
- [ ] https://github.com/eddie-energy/eddie/issues/455
- [ ] https://github.com/eddie-energy/eddie/issues/744
- [ ] https://github.com/eddie-energy/eddie/issues/788
- [ ] https://github.com/eddie-energy/eddie/issues/789
- [ ] https://github.com/eddie-energy/eddie/issues/790
- [ ] https://github.com/eddie-energy/eddie/issues/791
- [ ] https://github.com/eddie-energy/eddie/issues/782
