### ISSUE TITLE
Epic: Merge the Permission Facade prototype into the main repo

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#67]
```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/71
- [ ] https://github.com/eddie-energy/eddie/issues/69
- [ ] https://github.com/eddie-energy/eddie/issues/70
- [ ] https://github.com/eddie-energy/x-consent-module-prototype/issues/8
- [ ] https://github.com/eddie-energy/eddie/issues/83
- [ ] https://github.com/eddie-energy/x-consent-module-prototype/issues/10
- [ ] https://github.com/eddie-energy/x-consent-module-prototype/issues/11
```
