### ISSUE TITLE
Handle historical data for FI and EE

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#675]
## Short Description
The region connectors FI (Fingrid) and EE (Elering) can handle historical data.

## Acceptance Criteria
- [x] FI: Data from Fingrid can be requested and received.
- [x] FI: Users can accept or decline data requests.
- [ ] EE: Data from Elering can be requested and received.
- [ ] EE: Users can accept or decline data requests. 

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/486
- [ ] https://github.com/eddie-energy/eddie/issues/279
```
