### ISSUE TITLE
Provide a logo for each permission administrator

### ISSUE THREAD

**Issue by georghartner** [eddie-energy/eddie#711]
## Short Description

Make it possible to show a logo for the selected PA in the permission dialog. This logo should be managed through the [BPRT region roles spreadsheet](https://hartnerconsultingcom.sharepoint.com/:x:/r/sites/EuropeanDataAccess/_layouts/15/Doc.aspx?sourcedoc=%7BF180C1F9-8FC1-4A11-8260-766F417D592A%7D&file=BPRT_Region_Roles.xlsx&action=default&mobileredirect=true).

This mainly concerns regions with multiple PAs like EDA (AT) or Green Button (US/CA).

## Acceptance Criteria

- [ ] Make it possible to upload a logo for each PA and MDA
- [ ] Logo is displayed in the permission dialog after selecting the PA
- [ ] Logos can be retrieved from the PA metadata API

## Tasks
- [ ] Define a way to reference logos in region roles spreadsheet
- [ ] Collect logos from permission administrators
- [ ] Display the logo of the permission administrator if provided
