### ISSUE TITLE
Contribute to upcoming deliverables

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#743]
## Short Description
The deliverables D2.2, D3.1, D4.1, D5.1, D8.3 are finished.

## Acceptance Criteria
- [x] D2.2 is finished
- [x] D3.1 is finished
- [x] D4.1 is finished
- [x] D5.1 received contributions to the chapter 'Status of region connectors'
- [x] D8.3 is finished

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/751
- [ ] https://github.com/eddie-energy/eddie/issues/750
- [ ] https://github.com/eddie-energy/eddie/issues/759
- [ ] https://github.com/eddie-energy/eddie/issues/758
- [ ] https://github.com/eddie-energy/eddie/issues/760
- [ ] https://github.com/eddie-energy/eddie/issues/757
- [ ] https://github.com/eddie-energy/eddie/issues/761
- [ ] https://github.com/eddie-energy/eddie/issues/756
- [ ] https://github.com/eddie-energy/eddie/issues/765
```
