### ISSUE TITLE
Epic (T3.4.1): Provide in-house permission administration

### ISSUE THREAD

**Issue by p42294-fhooe** [eddie-energy/eddie#815]
# Intended outcome

The goal of this epic is to create a permission management system that runs on AIIDA.
It should provide capabilities to manage permissions related to near real-time data.
Integration with EDDIE is necessary to be able to setup a new permission with an EP.

## API
The permission management should be available via a HTTP REST API, allowing different frontends to be built around it (e.g., website & app).

### Features
- Set up a new permission
- View existing permissions
- Customer terminates a permission 
- EP terminates a permission
- Resume a terminated permission

#### Setup new permission
The following workflow shall be possible:
Assume that the EP has configured a service that requires near real-time smart meter data.

1. A customer visits an EP's website and clicks on "Connect my data".
2. Similar to the historical validated data (HVD) process, a EDDIE popup or iframe (etc.) shows up.
   Instead of the input mask for e.g., the metering point or DSO that would show for HVD data, a QR code is displayed.
4. The customer scans the QR code with the app, and confirms the list of data, timeframe, resolution, etc... that is shared.
   Alternatively, the information embedded in the QR code can be copied as e.g. JSON or BASE64 string and pasted in a "set up new permission" window of the AIIDA-local website
5. The app communicates with the AIIDA instance on the same network and sends it the information about this new permission.
6. AIIDA stores the permission information and starts streaming data to the EDDIE framework of the EP.

##### Two approaches:
- QR code contains all necessary information
	- Large
	- Scanning could become difficult, although it's good quality on a screen
	- Maybe not possible if e.g. certificates, etc. need to be embedded
		- [Apparently limit is 2953 bytes](https://tritonstore.com.au/qr-code-size/)
- QR code contains only handshake URL
	- Small & clean code
	- Handshake needs to be executed before user confirmation
		- Adds a bit of delay
	- No limits on which data and how much data is exchanged

--> For now, all necessary information will be encoded in the QR code, as it's easier to implement.

#### View existing permissions
- A list of permissions with all user relevant information should be available via the REST API and be displayed in the UI.
- Relevant information includes e.g., start & end of permission, current status, which data is shared, sharing interval & resolution.

#### Customer terminates a permission
- Via any UI, the customer should be able to terminate any currently running permission, as well as any permission that hasn't started yet (i.e., the startDate for sharing data is in the future).
	- The UI sends the termination request to the API of AIIDA.
	- In the case of a termination, a corresponding message informing the EP's EDDIE framework about the cancellation should be sent. See [here](https://github.com/eddie-energy/eddie/wiki/EDDIE-Consent-Facade-Specification#revocation-of-a-consent-by-the-customer-implicitly-or-explicitly) for the process model for HVD data, which should be similarly implemented for near real-time data.

#### EP terminates a permission
- Like the customer, the EP can also cancel any currently running permission by sending a special termination request to the customer's AIIDA instance.
- If a permission has been accepted by the customer, but data sharing hasn't been started yet because the start date is in the future, it's not possible for the EP to cancel the permission. This is due to a technical reason, as the EP can't send a message to AIIDA, but AIIDA has to initiate the connection and from AIIDA's point of view, there is no reason to establish a connection if no data needs to be shared yet.
This requirement is also described [here](https://github.com/eddie-energy/eddie/wiki/EDDIE-Consent-Facade-Specification) and eddie-energy/eddie#235.

#### Resume a terminated permission
Users might "accidentally" or unknowingly terminate a permission for an EP's service.
We want to give them the opportunity to "undo" a permission termination, but at a later point in time, when the permission process is updated.
The EP should be able to configure if a resumption is possible.

## Requirements for the EDDIE framework
- A web frontend that is shown after "Connect my data" is clicked (similar to micro-front-ends from region connectors).
	- A configurable backend similar to a region connector (configure which data, timeframe, etc...)
	- The backend generates the QR code and the frontend displays it.
	- The QR code should contain a *connectionId*, that is sent along with each streaming message and allows EDDIE/the EP to associate messages.
	  This id should be made accessible to the EP.
- ~~An HTTP server for the handshake if a handshake is used.~~

## UI
As AIIDA provides this permission management via a HTTP REST API, a UI needs to be created.
Two possible UIs are envisaged:
- An app
	- This app should be the same app as the one for the marketplace
- Website
	- AIIDA should host a web server that provides a web UI to manage permissions.
	  This possibility is important as not every customer may have a smartphone on which they can install the app, or they don't want to use the app.
	- This website is also used to e.g., configure data sources (see other AIIDA epics).

Both UIs should be of similar design as the UI from the HVD process, providing the customer with a streamlined UI/UX, regardless of the type of data they are granting permission.

Prioritize website as app needs marketplace or use basic app implementation that will change?
--> Prioritize the website because it's easier to demonstrate in Madrid.

## Preliminary definition of permission object

![Image](https://github.com/eddie-energy/aiida/assets/123056348/051eaebb-f764-4149-8daf-17534f3964eb)

![Image](https://user-images.githubusercontent.com/123056348/258781661-71ce2e9a-18ad-45d2-a440-34e343aa34df.png)

#### Permission status state diagram
Should be similar to [this process model diagram](https://github.com/eddie-energy/eddie/wiki/EDDIE-Consent-Process-Model), but some states, like WAITING_FOR_START, need to be added.

## Notes
- (Field) Names are not final.
- Implement the permission flow where there is a direct connection between AIIDA & App possible or via the website served by AIIDA.
  Capabilities to setup offers with help of the marketplace aren't part of this epic.
- For this epic, AIIDA needs to be setup on the local network.
  

## Further questions
- If the customer rejects a permission, should it still be persisted in the database? (Ignore for now)
- What needs to be integrated into the admin dashboard?

## Tasks
```[tasklist]
### Tasks
- [ ] eddie-energy/eddie#820
- [ ] https://github.com/eddie-energy/eddie/issues/822
- [ ] https://github.com/eddie-energy/eddie/issues/255
- [ ] eddie-energy/eddie#256
- [ ] https://github.com/eddie-energy/eddie/issues/836
- [ ] https://github.com/eddie-energy/eddie/issues/840
```
