### ISSUE TITLE
Implement Kafka streamer

### ISSUE THREAD

**Issue by p42294-fhooe** [eddie-energy/eddie#830]
# Intended outcome
## What
Implement a Kafka client, that connects to a Kafka broker running in the EP infrastructure.
The streamer gets a _Flux\<AiidaRecord>_ to which it subscribes for messages that should be sent via Kafka to the EP.
The necessary Kafka configuration parameters are saved in the *Permission*.

There are three different topics:
- _dataTopic_: On this topic, only messages containing actual measurement data should be published
- _statusTopic_: On this topic, messages regarding the status of the permission (e.g. ACCEPTED, REVOKED) should be sent
- _subscribeTopic_: The KafkaStreamer should subscribe to this topic. If the EP wants to terminate a permission, it will produce an according message to this topic and the KafkaStreamer of AIIDA should receive and process this message.

## Why
The EP wants to receive near real-time data via Kafka.

## Related
- https://github.com/eddie-energy/eddie/issues/816

## Notes
- As no CIM for near real-time data is available now, sending a JSON representation of the *AiidaRecord* suffices.
- No authentication/authorization required for now.
- Needs investigation, how failures are handled.
  - Kafka can automatically retry publishing messages, but what should happen after e.g. 5 retries?
  - Additionally, in the case of a shutdown/restart, all unsent messages will be lost --> how should this be handled?

## Estimation

# Acceptance criteria

```[tasklist]
### Tasks
- [ ] eddie-energy/aiida#23
- [ ] https://github.com/eddie-energy/eddie/issues/832
- [ ] https://github.com/eddie-energy/eddie/issues/833
```
