### ISSUE TITLE
Epic (T3.4.2): Connect, read and decrypt data from the smart meter

### ISSUE THREAD

**Issue by p42294-fhooe** [eddie-energy/eddie#835]
# Epic read smart meter
# Intended outcome
The goal of this epic is to be able to read and decrypt data from various smart meter models in the EU.

## Connection
As EDDIE has no intent to create a specialized hardware, the customer is responsible for the physical connection between the PC running AIIDA and their smart meter.
Due to the diversity of the models deployed throughout the European Union, there are many different physical connectors, e.g., M-Bus, wM-Bus, DSMR, IR,...
From AIIDA's perspective this is irrelevant as the customer makes the connection.
AIIDA should support reading data from serial ports, i.e., the customer connects the smart meter via a cable like [this](https://de.aliexpress.com/item/32954035005.html?gatewayAdapt=gloMsite2deuPcglo2deu), and then AIIDA can read the smart meter data from a serial port.
[A library](https://fazecast.github.io/jSerialComm/) is required to read serial ports in Java.
Other data sources like the [Oesterreichs Energie smart meter adapter](https://oesterreichsenergie.at/fileadmin/user_upload/Oesterreichs_Energie/Publikationsdatenbank/Leitfaden/2022/Datenblatt_Smart_Meter_Adapter_final_20220209.pdf) shall be supported as well. This particular adapter supports REST and MQTT, whereas MQTT is the preferred way to connect it, as AIIDA can be notified if new data is available.

## Protocols
Different meter models employ different protocols, common protocols are:
- DSMR
- M-Bus
- DLMS/COSEM

See [this Excel sheet](https://hartnerconsultingcom.sharepoint.com/:x:/r/sites/EuropeanDataAccess/_layouts/15/doc2.aspx?sourcedoc=%7BF180C1F9-8FC1-4A11-8260-766F417D592A%7D&file=BPRT_Region_Roles.xlsx&action=default&mobileredirect=true&cid=f4f2ec85-8fa5-4d57-a8c6-ccc89a8084c4) for a list of meters and their protocols.
The customer needs to enter which meter model they have, so AIIDA can interpret the data correctly.
A master data list has to be created. Ideally, the customer selects their country and only relevant DSOs are shown. Then they select their DSO or meter model, pictures can help them to identify the correct one.
Once the customer selects their meter model, certain parameters like baud rate, number of start/stop bits are then extracted from the master data.
Some meters encrypt their output, therefore support for entering the decryption key has to be provided as well.

## UI  & REST API
A UI and REST API need to be created that support
- adding a smart meter as data source
- configuring which meter model is used
- setting encryption keys
- overview of the data source

The UI should be integrated with the UIs from other AIIDA epics.

## Data Storage
Data from the smart meters should be persisted in a database.
Each record should at least include:
- Timestamp of measurement
- Value
- Identifier of the measured medium/quantity/value --> OBIS code

For now, focus only on smart meter data, which allows the following data model:
![Image](https://github.com/eddie-energy/eddie/assets/123056348/4cc4c3b3-0324-403a-b359-ea3b4eb6eef4)

Which concrete subclass of *AiidaRecord* should be used depends on the OBIS code.
A mapping between OBIS code and datatype has to be provided, preferably in a separate file than hardcoded in the Java code.

## Priority list
1. Oesterreichs Energie smart meter adapter
2. NetzOÖ AMIS meter (IR)
3. Linky
4. Italian?

## Notes
- For Austrian smart meters, the near real-time data output has to be activated by contacting the DSO. It might take weeks until they activate it.
The required decryption key is also available from the DSO.
- At least 10 meter models have to be supported: eddie-energy/eddie#244

## Prerequisites
- Example data for the different smart meters
- Smart meters for testing
- Oesterreichs Energie Adapter

## Tasks
- [x] eddie-energy/eddie#819
- [x] eddie-energy/eddie#826
- [x] eddie-energy/eddie#825
- [x] https://github.com/eddie-energy/eddie/issues/842
- [x] https://github.com/eddie-energy/eddie/issues/846
- [x] https://github.com/eddie-energy/eddie/issues/849
- [x] https://github.com/eddie-energy/eddie/issues/1184
