### ISSUE TITLE
Create StreamerManager to handle AiidaStreamer lifecycles

### ISSUE THREAD

**Issue by p42294-fhooe** [eddie-energy/eddie#837]
# Intended outcome
## What
Create a class *StreamerManager* that handles the creation and of AiidaStreamers (currently only KafkaStreamer) for a given permission and exposes methods that can be called by e.g. the service layer.

The following functionality should be implemented:
- Create a new streamer when a permission is accepted
- Send a *ConnectionStatusMessage*
- Stop streaming data when the customer revokes a permission
- Automatically stop streaming data when the end time of a permission has been reached
- Stop streaming data when the EP requests a termination
- Recreate and start streamers for permissions that have not yet expired on startup

## Why
Separate the concerns by using a dedicated class that manages the construction and destruction of AiidaStreamer objects and allow other layers (e.g. service layer) to invoke the functionalities.

## Prerequisites/Blockers
- eddie-energy/eddie#830
 

## Estimation

# Acceptance criteria
```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/838
- [ ] https://github.com/eddie-energy/eddie/issues/839
- [ ] https://github.com/eddie-energy/eddie/issues/844
- [ ] https://github.com/eddie-energy/eddie/issues/843
```
