### ISSUE TITLE
Require authentication for Datadis PATCH requests

### ISSUE THREAD

**Issue by p42294-fhooe** [eddie-energy/eddie#876]
## Context
For Datadis requests, we show two buttons on the frontend, one of which the customer should press once they have accepted the permission request in the Datadis portal.
These buttons result in a PATCH request to, e.g. */region-connectors/es-datadis/{ID}/accepted*.
Currently, no authentication check is made, so if somebody would know the randomly generated UUID, they could cause a state change of the permission request, even if they are not the person that initiated the permission request.

## TODO
Implement authentication, that ensures only the customer that created a certain permission request may cause an accept/reject state change.
This can be done e.g. by setting a session cookie when a request to */permission-request* is made, and only accepting PATCH requests for that permission, if the same session cookie is included in the PATCH request.
Spring Security has good support for session management.
According to @re1, for this case we have no problem with third party cookies, as the requests are made by the popup to the same domain as itself is loaded from.

## Acceptance criteria
- [ ] Only the customer that created a permission request may cause state changes for that permission
- [ ] 401 returned if a PATCH request to */{ID}/accepted* or */{ID}/rejected* does not contain any authentication
- [ ] 403 returned if a PATCH request contains a different authentication than what is expected for that permission
- [ ] Error messages similar to other error responses
- [ ] Notify Georg when this is merged
