### ISSUE TITLE
Use MQTT instead of Kafka for AIIDA

### ISSUE THREAD

**Issue by p42294-fhooe** [eddie-energy/eddie#902]
## Short Description
Switch the transport protocol from Kafka to MQTT.

## Blockers
- #432 

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/950
- [ ] https://github.com/eddie-energy/eddie/issues/944
- [ ] https://github.com/eddie-energy/eddie/issues/951
- [ ] https://github.com/eddie-energy/eddie/issues/949
- [ ] https://github.com/eddie-energy/eddie/issues/975
- [ ] https://github.com/eddie-energy/eddie/issues/963
- [ ] https://github.com/eddie-energy/eddie/issues/972
- [ ] https://github.com/eddie-energy/eddie/issues/920
- [x] Update documentations and readme
- [x] Update E2E tests, start MQTT broker
- [ ] https://github.com/eddie-energy/eddie/issues/977
- [ ] https://github.com/eddie-energy/eddie/issues/978
- [ ] https://github.com/eddie-energy/eddie/issues/976
- [ ] https://github.com/eddie-energy/eddie/issues/929
- [ ] https://github.com/eddie-energy/eddie/issues/1071
```
