### ISSUE TITLE
Improve developer experience and production builds for web components

### ISSUE THREAD

**Issue by re1** [eddie-energy/eddie#935]
## Short Description

This requirement collects issues towards an improved build process for web components, specifically the EDDIE button and region connector (RC) elements. The main goals are to improve upon:
- Production builds
  - Cache elements using their hash code
  - Share libraries (Lit) across RC elements
  - Chunk similar implementations across RC elements
- Developer experience
  - Hot reloads during development of the button and RC elements
  - Typings and contract definitions for common/shared objects and methods
  - Improved debugging with source maps

## Acceptance Criteria
- [ ] Elements are cached using their hash-code
- [ ] No change in interaction for the end user

## Blockers

Not blocked by any issues.

## Design/UI/UX Requirements _(optional)_

Changes will not result in visual changes.

## Tasks
- [x] https://github.com/eddie-energy/eddie/issues/464
- [ ] https://github.com/eddie-energy/eddie/issues/937
- [ ] https://github.com/eddie-energy/eddie/issues/908
- [ ] https://github.com/eddie-energy/eddie/issues/1440
- [ ] Use a constant Shoelace version across core and RC elements
- [ ] Share web dependencies across RC elements
- [ ] Chunk similar implementations across RC elements
- [ ] Hot-reload web assets in development
- [ ] Add typings and define contracts for implementations shared across RC elements
