### ISSUE TITLE
Implement an application for testing/demonstration purpose

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#936]
## Short Description
An application shall be implemented which can be used for testing and to showcase the functionality of EDDIE. Therefore, the app must provide features to request and receive consumption data via the EDDIE framework, to handle dataneeds, to display consumption data properly (historical and near real-time).

## Additional Dataneed Infos
- see the following [recording](https://hartnerconsultingcom.sharepoint.com/sites/EuropeanDataAccess/_layouts/15/stream.aspx?id=%2Fsites%2FEuropeanDataAccess%2FFreigegebene%20Dokumente%2FMeetings%2FDevelopment%20Team%20Meetings%2F2024%2D02%2D07%5FFocus%5FSession%5FDataneeds%2F20240207%5FFocus%20session%5F%20Dataneeds%5Frefactoring%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Eea893c44%2D49cb%2D43fc%2D8062%2D888d0b19fd4c)

## Acceptance Criteria
- [ ] permission requests can be created for supported region connectors 
- [ ] permission requests can be created for AIIDA test instances
- [ ] received consumption data can be displayed in a diagram (also consider near real-time data)
- [ ] dataneeds can be create/delete/modify
- [ ] Kafka is used to receive consumption data
- [ ] Kafka is used to receive and display status information
- [ ] consumption data is stored in a POSTGRES / timescale database
- [ ] simple user handling: There are 3 test users and 1 admin user to be chosen from.
- [ ] admin user can dynamically assign different dataneeds to a service.
- [ ] There are 2 fixed dataneeds (e.g. one for 3 days back, the other one for AIIDA), and a 3rd dataneed that is assigned dynamically to a service by the admin user.
- [ ] service to which a dataneed can be assigned dynamically as admin user

## Design/UI/UX Requirements _(optional)_
- First ideas in figma board [here](https://www.figma.com/design/RG5Fjes55wtoHL1N4KIyaq/Demo-App?node-id=0-1&t=0C7TkINHLMiTLdKf-0)

## Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/1077
- [ ] https://github.com/eddie-energy/eddie/issues/1078
- [ ] #1080
- [ ] https://github.com/eddie-energy/eddie/issues/1082
- [ ] https://github.com/eddie-energy/eddie/issues/1081
- [ ] #1083
- [x] #1084
