### ISSUE TITLE
Implement an application to administrate permissions

### ISSUE THREAD

**Issue by sgrue** [eddie-energy/eddie#938]
## Short Description
An application shall be implemented which can be used to for the basic administration of the permissions. Therefore, the app must provide a list of all permissions and display them with detailed information (country, PA, ID, metering point, ...). Additionally, there must be an option where a permission can be terminated manually.
Information about permissions and their status is available via Kafka on the topic `consent-market-document`.
See the [docs](https://github.com/eddie-energy/eddie/tree/main/docs) folder for documentation & schemas.
Termination messages should be sent to the Kafka topic `terminations`, see the bottom of [OPERATION.md](https://github.com/eddie-energy/eddie/blob/main/docs/OPERATION.md) for an example message.

## Acceptance Criteria
- [ ] information about permission is retrieved via Flux
- [ ] all permissions are stored in a POSTGRES database
- [ ] all permissions can be displayed with their current status (Name, ID, when it is valid, metering point, granularity, timestamp of its creation)
- [ ] there is an option to terminate an active permission
- [ ] Show terminate button only for permissions in an eligible state (cf. [process model](https://github.com/eddie-energy/eddie/wiki/EDDIE-Permission-Process-Model))
- [ ] (??? setup/config region connectors)

## Design/UI/UX ideas
The following image shows the draft from the grant agreement as a starting point:

![image](https://github.com/eddie-energy/eddie/assets/42996364/f34b107f-5ae2-4872-8e3c-3e90f71b7a70)

```[tasklist]
### Tasks
- [ ] https://github.com/eddie-energy/eddie/issues/939
- [ ] #940
- [ ] #941
- [ ] #942
- [ ] #947
```
